#!/usr/bin/env python3
"""Run Agent Ledger with Python 3.10+ and no runtime dependencies."""
import argparse
import hashlib
import os
import sys
import sqlite3
import tempfile
import webbrowser
from pathlib import Path
from lens import __version__
from lens.demo import write_demo
from lens.locking import import_lock
from lens.importer import Importer
from lens.server import LocalServer
from lens.storage import connect


def parser():
    p = argparse.ArgumentParser(description='Recover coding-agent context and understand local usage. No model or account required.')
    p.add_argument('--version', action='version', version=__version__)
    p.add_argument('--codex-home', type=Path, help='History root (then CODEX_HOME, then ~/.codex)')
    p.add_argument('--claude-home', type=Path, help='Claude history root (default: ~/.claude); only projects/ is read')
    p.add_argument('--no-claude', action='store_true', help='Exclude Claude history')
    p.add_argument('--mcp', action='store_true', help='Serve read-only MCP tools over stdio; no scan or browser')
    p.add_argument('--mcp-config', action='store_true', help='Print the optional MCP connection configuration and exit')
    p.add_argument('--database', type=Path, help='Existing Ledger database for MCP; generated by connection setup')
    p.add_argument('--add', type=Path, help='Save one UTF-8 .txt or .md file as project context (max 32,000 characters)')
    p.add_argument('--project', default='', help='Exact project path for --add; omitted means global context')
    p.add_argument('--watch', type=int, default=0, metavar='SECONDS', help='Refresh while the local app runs (minimum 15 seconds; default: manual)')
    p.add_argument('--cache-dir', type=Path, help='Private cache directory (default: platform user cache)')
    p.add_argument('--no-open', action='store_true', help='Print local URL without opening a browser')
    p.add_argument('--demo', action='store_true', help='Use only synthetic data in a temporary directory')
    p.add_argument('--line-limit-mib', type=int, default=8, choices=range(1,65), metavar='1..64', help='Skip larger JSONL records (default: 8 MiB)')
    p.add_argument('--preview-chars', type=int, default=4096, help='Observed-text preview bound (256..65536; default: 4096)')
    p.add_argument('--import-only', action='store_true', help='Import and exit without starting the server')
    return p


def default_cache():
    if sys.platform == 'win32':
        base = Path(os.environ.get('LOCALAPPDATA', str(Path.home()/'AppData'/'Local')))
    elif sys.platform == 'darwin':
        base = Path.home()/'Library'/'Caches'
    else:
        base = Path(os.environ.get('XDG_CACHE_HOME', str(Path.home()/'.cache')))
    return base/'agent-ledger'


def run(args, demo_root=None):
    home = (args.codex_home or Path(os.environ.get('CODEX_HOME', str(Path.home()/'.codex')))).expanduser().resolve()
    claude = (args.claude_home or Path.home()/'.claude').expanduser().resolve()
    if demo_root:
        claude = demo_root/'claude'
        from lens.demo_memory import write_memory_demo
        write_memory_demo(claude)
        home = demo_root/'history'; write_demo(home)
    cache = (demo_root/'cache' if demo_root else (args.cache_dir or default_cache())).expanduser().resolve()
    # An explicit cache inside a history root risks importing generated data or modifying Codex state.
    if any(cache == root or root in cache.parents for root in (home,claude)):
        raise ValueError('Cache must be outside agent history roots; choose a separate --cache-dir.')
    db_path = cache/('ledger-v1-'+hashlib.sha256((str(home)+'|'+('' if args.no_claude else str(claude))).encode()).hexdigest()[:16]+'.sqlite3')
    if args.database:
        if not args.mcp:
            raise ValueError('--database is only supported with --mcp')
        db_path=args.database.expanduser().resolve()
        if not db_path.is_file():
            raise ValueError('Index missing. Run ledger.py once before connecting an agent.')
    if args.mcp_config:
        import json
        from lens.mcp import config
        print(json.dumps(config(db_path),indent=2)); return
    if args.mcp:
        if not db_path.is_file():raise ValueError('Index missing. Run ledger.py once before connecting an agent.')
        from lens.mcp import serve
        serve(db_path); return
    cache.mkdir(parents=True, exist_ok=True, mode=0o700)
    if args.add:
        from lens.memory import Memory
        if args.add.suffix.lower() not in ('.md','.txt') or args.add.stat().st_size>128000:
            raise ValueError('Choose a UTF-8 .md or .txt file up to 32,000 characters.')
        text=args.add.read_text(encoding='utf-8')
        db=connect(db_path)
        try:
            result=Memory(db).save_note({'title':args.add.stem,'text':text,'project':args.project})
            print('Saved '+result['reference'])
        finally:db.close()
        return
    def refresh():
        with import_lock(str(db_path)+'.lock'):
            db = connect(db_path)
            try:
                from lens.claude import ClaudeImporter
                from datetime import datetime, timezone
                def progress(message):
                    print(message, flush=True)
                result = Importer(db, home, args.line_limit_mib*1024*1024, args.preview_chars, progress).run()
                if not args.no_claude:
                    other = ClaudeImporter(db,claude,args.line_limit_mib*1024*1024,args.preview_chars,progress).run()
                    for key in ('records','discovered','changed'):result[key]+=other[key]
                    result['issues']+=other['issues']
                db.execute("INSERT OR REPLACE INTO metadata VALUES('refreshed',?)",(datetime.now(timezone.utc).isoformat(),))
                db.commit()
                return result
            finally:
                db.close()
    print('Preparing your local index. The first import can take several minutes for large histories.\n'
          'Existing checkpoints are reused; there is no need to delete the cache.\n'
          + ('Import-only mode: no browser will open.' if args.import_only else
             'The workspace opens after indexing finishes. A previously opened demo tab is separate.'), flush=True)
    imported = refresh()
    print(f"Imported {imported['records']:,} records; {imported['discovered']:,} sources; {imported['changed']:,} changed.")
    for issue in imported['issues']:
        print(issue)
    if args.import_only:
        return
    with LocalServer(db_path, refresh, imported, bool(demo_root)) as server:
        print('\nREADY — Agent Ledger '+('synthetic demo' if demo_root else 'your real history')+'\n'+server.url+'\nOpen this full URL to view this workspace.\nKeep this process running. Ctrl+C stops the server.', flush=True)
        if not args.no_open:
            try:
                if not webbrowser.open(server.url):
                    print('Browser did not open. Paste the URL above into your browser.')
            except webbrowser.Error:
                print('Browser unavailable. Paste the URL above into your browser.')
        if args.watch:
            import threading
            stop=threading.Event()
            def watch():
                while not stop.wait(args.watch):
                    with server.lock:
                        try:server.import_report=refresh()
                        except (OSError,ValueError,sqlite3.Error):
                            server.import_report={'issues':['Background refresh failed; try Refresh or check cache permissions.']}
            worker=threading.Thread(target=watch,daemon=True);worker.start()
        try:
            server.serve_forever(poll_interval=0.25)
        except KeyboardInterrupt:
            print('\nWorkspace stopped.')
        finally:
            if args.watch:stop.set();worker.join(timeout=5)


def main():
    args = parser().parse_args()
    if args.watch and args.watch<15:parser().error('--watch must be at least 15 seconds')
    if args.mcp and (args.demo or args.add or args.watch or args.mcp_config):parser().error('--mcp cannot be combined with demo, add, watch, or mcp-config')
    if not 256 <= args.preview_chars <= 65536:
        parser().error('--preview-chars must be between 256 and 65536')
    if hasattr(os, 'umask'):
        os.umask(0o077)
    try:
        if args.demo:
            with tempfile.TemporaryDirectory(prefix='codex-usage-lens-demo-') as temp:
                run(args, Path(temp))
        else:
            run(args)
        return 0
    except KeyboardInterrupt:
        print('\nImport interrupted. Committed checkpoints will resume next run.'); return 130
    except (OSError, ValueError, sqlite3.Error) as error:
        # No raw exception/path or transcript dump by default.
        print('Could not start workspace. Check history/cache permissions and available disk space.',file=sys.stderr)
        if isinstance(error, ValueError):
            print(str(error),file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
